---
info:
  title: Rex
  description: Rex provides a variety of classes useful for security testing and exploit
    development.
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/rex
  x-cortex-tag: rex
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: metasploit
openapi: 3.0.1
servers:
- url: "/"
